-- MySQL Script generated by MySQL Workbench
-- Mon Dec  3 18:21:20 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `facebook_id` BIGINT NULL,
  `forgotten_password_key` CHAR(50) NULL,
  `forgotten_password_key_expires_on` DATETIME NULL,
  `activation_key` CHAR(50) NULL,
  `is_active` TINYINT(1) NULL DEFAULT 0,
  `last_logged_on` DATETIME NULL,
  `can_delete` TINYINT(1) NULL,
  `created_on` TIMESTAMP NULL,
  `last_active_on` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`country` ;

CREATE TABLE IF NOT EXISTS `mydb`.`country` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(3) NULL,
  `latin_name` VARCHAR(255) NULL,
  `lat` VARCHAR(20) NULL,
  `lon` VARCHAR(20) NULL,
  `can_delete` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `latin_name_UNIQUE` (`latin_name` ASC),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`city` ;

CREATE TABLE IF NOT EXISTS `mydb`.`city` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `country_id` SMALLINT UNSIGNED NOT NULL,
  `place_id` VARCHAR(255) NULL,
  `name` VARCHAR(255) NOT NULL,
  `lat` VARCHAR(20) NOT NULL,
  `lon` VARCHAR(20) NOT NULL,
  `can_delete` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_city_country1_idx` (`country_id` ASC),
  CONSTRAINT `fk_city_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `mydb`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_profile` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_profile` (
  `user_id` BIGINT UNSIGNED NOT NULL,
  `first_name` VARCHAR(100) NULL,
  `last_name` VARCHAR(100) NULL,
  `profile_image_url` VARCHAR(2500) CHARACTER SET 'latin1' COLLATE 'latin1_swedish_ci' NULL,
  `headline` VARCHAR(255) NULL,
  `country_id` SMALLINT UNSIGNED NULL,
  `city_id` INT UNSIGNED NULL,
  INDEX `fk_user_profile_country1_idx` (`country_id` ASC),
  PRIMARY KEY (`user_id`),
  INDEX `fk_user_profile_city1_idx` (`city_id` ASC),
  CONSTRAINT `fk_user_profile_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `mydb`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_profile_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_profile_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `mydb`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_settings` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_settings` (
  `user_id` BIGINT UNSIGNED NOT NULL,
  `email_notifications` TINYINT(1) NOT NULL DEFAULT 1,
  `email_monthly_newsletter` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_user_settings_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_session` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_session` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `jti` VARCHAR(36) NOT NULL,
  `token_type` VARCHAR(10) NOT NULL,
  `user_identity` BIGINT NOT NULL,
  `revoked` TINYINT NOT NULL,
  `expires` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_session_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_session_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb`;

DELIMITER $$

USE `mydb`$$
DROP TRIGGER IF EXISTS `mydb`.`user_AFTER_INSERT` $$
USE `mydb`$$
CREATE TRIGGER `user_AFTER_INSERT` AFTER INSERT ON `user` FOR EACH ROW
BEGIN
	# Create a few tables automatically when we create a new user.
		# Settings
		INSERT INTO `user_settings` (`user_settings`.user_id) VALUES (NEW.id);					
        INSERT INTO `user_profile` (`user_profile`.user_id) VALUES (NEW.id);					
END$$


USE `mydb`$$
DROP TRIGGER IF EXISTS `mydb`.`user_BEFORE_DELETE` $$
USE `mydb`$$
CREATE TRIGGER `user_BEFORE_DELETE` BEFORE DELETE ON `user` FOR EACH ROW
BEGIN
	# Check if the deletion of this record is allowed. For that purpose the flag “can_delete” must be true.
    IF OLD.can_delete IS FALSE THEN
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'You may not delete this item.';
    ELSE		
		# Profile
		DELETE FROM `user_profile` WHERE OLD.id = `user_profile`.user_id;
		# Settings
		DELETE FROM `user_settings` WHERE OLD.id = `user_settings`.user_id;		
		# Sessions
		DELETE FROM `user_session` WHERE OLD.id = `user_session`.user_id;		
        # Elements assigned to the user
		DELETE FROM `users_element` WHERE OLD.id = `users_element`.user_id;		
    END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`country`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (1, 'AF', 'Afghanistan', '33.8612093', '63.2010711', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (2, 'AX', 'Åland Islands', '60.1990437', '19.8231942', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (3, 'AL', 'Albania', '41.1495133', '19.0367607', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (4, 'DZ', 'Algeria', '27.7527395', '-7.3700584', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (5, 'AS', 'American Samoa', '-14.3058438', '-170.7663933', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (6, 'AD', 'Andorra', '42.5424371', '1.4572455', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (7, 'AO', 'Angola', '-11.1689222', '13.3717013', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (8, 'AI', 'Anguilla', '18.2234209', '-63.1268455', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (9, 'AQ', 'Antarctica', '-65.8301374', '-53.1959316', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (10, 'AG', 'Antigua and Barbuda', '17.0872127', '-61.8537029', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (11, 'AR', 'Argentina', '-36.9846454', '-81.6491677', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (12, 'AM', 'Armenia', '40.0672916', '43.9169031', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (13, 'AW', 'Aruba', '12.5177227', '-70.0360521', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (14, 'AC', 'Ascension Island', '-7.9411472', '-14.393142', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (15, 'AU', 'Australia', '-25.2394842', '115.0381535', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (16, 'AT', 'Austria', '47.6782117', '11.0975904', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (17, 'AZ', 'Azerbaijan', '40.1489465', '46.5683682', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (18, 'BS', 'Bahamas', '24.0753184', '-78.842829', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (19, 'BH', 'Bahrain', '25.9437723', '50.3206241', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (20, 'BD', 'Bangladesh', '23.6791178', '88.0950162', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (21, 'BB', 'Barbados', '13.1904286', '-59.6759925', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (22, 'BY', 'Belarus', '53.699155', '25.7297977', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (23, 'BE', 'Belgium', '50.4974177', '3.3527329', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (24, 'BZ', 'Belize', '17.1902928', '-89.4836639', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (25, 'BJ', 'Benin', '9.3199717', '0.0602307', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (26, 'BM', 'Bermuda', '32.3191453', '-64.8372943', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (27, 'BT', 'Bhutan', '27.5315095', '89.8740316', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (28, 'BO', 'Bolivia', '-16.2254566', '-68.0555667', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (29, 'BA', 'Bosnia and Herzegovina', '43.9130114', '16.548352', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (30, 'BW', 'Botswana', '-22.2703911', '20.1822847', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (31, 'BV', 'Bouvet Island', '-54.4204601', '3.3244755', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (32, 'BR', 'Brazil', '-13.4968938', '-71.5686006', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (33, 'IO', 'British Indian Ocean Territory', '-7.3344475', '72.3540389', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (34, 'VG', 'British Virgin Islands', '18.4183634', '-64.7258596', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (35, 'BN', 'Brunei', '4.5248791', '114.4387491', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (36, 'BG', 'Bulgaria', '42.7218652', '24.3594928', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (37, 'BF', 'Burkina Faso', '12.2434684', '-3.8053281', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (38, 'BI', 'Burundi', '-3.3879957', '29.3634319', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (39, 'KH', 'Cambodia', '11.9843734', '102.7309617', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (40, 'CM', 'Cameroon', '7.3580251', '7.8368784', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (41, 'CA', 'Canada', '54.7155662', '-113.7695953', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (42, 'IC', 'Canary Islands', '28.4422634', '-16.9772109', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (43, 'CV', 'Cape Verde', '15.1204301', '-23.7456007', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (44, 'BQ', 'Caribbean Netherlands', '12.168672', '-68.4485247', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (45, 'KY', 'Cayman Islands', '19.3300248', '-81.3226414', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (46, 'CF', 'Central African Republic', '6.6198088', '18.6869795', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (47, 'EA', 'Ceuta and Melilla', '35.8903725', '-5.3166679', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (48, 'TD', 'Chad', '15.4112274', '14.2282106', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (49, 'CL', 'Chile', '-35.3232434', '-89.1356221', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (50, 'CN', 'China', '34.5252218', '86.026295', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (51, 'CX', 'Christmas Island', '-10.4911916', '105.5528154', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (52, 'CP', 'Clipperton Island', '10.2833357', '-109.2176727', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (53, 'CC', 'Cocos (Keeling) Islands', '-12.1706935', '96.8066278', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (54, 'CO', 'Colombia', '4.1139542', '-77.4382369', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (55, 'KM', 'Comoros', '-11.6511721', '43.0917211', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (56, 'CD', 'Congo (DRC)', '-3.9613025', '12.6866229', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (57, 'CG', 'Congo (Republic)', '-0.6545825', '12.6485737', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (58, 'CK', 'Cook Islands', '-21.2356909', '-159.8124727', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (59, 'CR', 'Costa Rica', '9.6310801', '-85.378215', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (60, 'CI', 'Côte d’Ivoire', '7.5452378', '-7.7972586', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (61, 'HR', 'Croatia', '44.4533483', '14.220539', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (62, 'CU', 'Cuba', '21.5413551', '-81.7914656', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (63, 'CW', 'Curaçao', '12.2138187', '-69.0899975', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (64, 'CY', 'Cyprus', '35.1695756', '32.8751731', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (65, 'CZ', 'Czech Republic', '49.8001037', '14.3511781', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (66, 'DK', 'Denmark', '56.138153', '8.1852328', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (67, 'DG', 'Diego Garcia', '-7.3430524', '72.3587085', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (68, 'DJ', 'Djibouti', '11.8235722', '42.0267039', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (69, 'DM', 'Dominica', '15.4240445', '-61.500541', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (70, 'DO', 'Dominican Republic', '18.7002615', '-71.2887628', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (71, 'EC', 'Ecuador', '-1.7860182', '-80.3866143', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (72, 'EG', 'Egypt', '26.7742651', '26.2912715', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (73, 'SV', 'El Salvador', '13.8036897', '-89.4671718', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (74, 'GQ', 'Equatorial Guinea', '1.6208089', '9.7559436', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (75, 'ER', 'Eritrea', '15.1817108', '37.5385707', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (76, 'EE', 'Estonia', '58.6012654', '23.8636239', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (77, 'ET', 'Ethiopia', '9.1322241', '35.9918286', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (78, 'FK', 'Falkland Islands', '-51.7234024', '-60.641138', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (79, 'FO', 'Faroe Islands', '61.8920924', '-7.5347183', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (80, 'FJ', 'Fiji', '-17.4567122', '178.1343319', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (81, 'FI', 'Finland', '64.6533381', '17.1141459', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (82, 'FR', 'France', '46.1350676', '-2.2894058', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (83, 'GF', 'French Guiana', '3.9327373', '-54.2116123', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (84, 'PF', 'French Polynesia', '-17.6869427', '-149.513388', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (85, 'TF', 'French Southern Territories', '-49.1283978', '69.0175747', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (86, 'GA', 'Gabon', '-0.8152168', '9.3632553', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (87, 'GM', 'Gambia', '13.4321722', '-15.8650875', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (88, 'GE', 'Georgia', '42.3173294', '42.2475462', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (89, 'DE', 'Germany', '51.0847285', '5.9576626', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (90, 'GH', 'Ghana', '7.9563441', '-3.2803653', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (91, 'GI', 'Gibraltar', '36.1320102', '-5.3704699', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (92, 'GR', 'Greece', '38.2577532', '21.5615954', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (93, 'GL', 'Greenland', '68.5463295', '-74.9809632', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (94, 'GD', 'Grenada', '12.1101275', '-61.7637623', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (95, 'GP', 'Guadeloupe', '16.1736961', '-61.6866397', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (96, 'GU', 'Guam', '13.4489393', '144.6470297', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (97, 'GT', 'Guatemala', '15.7776261', '-91.3564768', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (98, 'GG', 'Guernsey', '49.4631158', '-2.6232175', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (99, 'GN', 'Guinea', '9.9306759', '-13.6077148', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (100, 'GW', 'Guinea-Bissau', '11.774253', '-15.7326652', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (101, 'GY', 'Guyana', '4.8574304', '-61.202746', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (102, 'HT', 'Haiti', '19.056158', '-73.6130719', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (103, 'HM', 'Heard and McDonald Islands', '-53.0762929', '73.3732377', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (104, 'HN', 'Honduras', '14.7504915', '-87.3660245', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (105, 'HK', 'Hong Kong', '22.3579352', '113.9805899', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (106, 'HU', 'Hungary', '47.1575349', '18.3819903', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (107, 'IS', 'Iceland', '64.9625735', '-21.2682623', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (108, 'IN', 'India', '20.9115937', '73.7310836', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (109, 'ID', 'Indonesia', '-2.4950908', '108.9509379', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (110, 'IR', 'Iran', '32.3499362', '49.1801953', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (111, 'IQ', 'Iraq', '33.1490232', '39.1821809', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (112, 'IE', 'Ireland', '53.4097028', '-10.579879', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (113, 'IM', 'Isle of Man', '54.2313465', '-4.8503661', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (114, 'IL', 'Israel', '31.4091676', '33.9578992', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (115, 'IT', 'Italy', '41.2131444', '8.0736575', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (116, 'JM', 'Jamaica', '18.1160089', '-77.8378347', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (117, 'JP', 'Japan', '34.4704136', '125.353306', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (118, 'JE', 'Jersey', '49.2112174', '-2.2028441', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (119, 'JO', 'Jordan', '31.2649734', '34.8807236', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (120, 'KZ', 'Kazakhstan', '47.6676257', '57.9128951', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (121, 'KE', 'Kenya', '0.1873444', '33.4004477', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (122, 'KI', 'Kiribati', '1.8712208', '-157.5034549', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (123, 'XK', 'Kosovo', '42.5629093', '20.3402809', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (124, 'KW', 'Kuwait', '29.314098', '46.9299303', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (125, 'KG', 'Kyrgyzstan', '41.2050687', '72.4902623', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (126, 'LA', 'Laos', '18.1984142', '101.6395105', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (127, 'LV', 'Latvia', '56.8629957', '22.358161', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (128, 'LB', 'Lebanon', '33.8734236', '35.3019378', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (129, 'LS', 'Lesotho', '-29.6160648', '27.1095926', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (130, 'LR', 'Liberia', '6.4352031', '-10.5464637', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (131, 'LY', 'Libya', '26.2734576', '12.764692', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (132, 'LI', 'Liechtenstein', '47.159566', '9.413209', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (133, 'LT', 'Lithuania (Lietuva)', '55.170003', '22.7711291', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (134, 'LU', 'Luxembourg', '49.8154033', '5.8524556', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (135, 'MO', 'Macau', '22.1634924', '113.5283596', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (136, 'MK', 'Macedonia (FYROM)', '41.1166095', '21.1121725', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (137, 'MG', 'Madagascar', '-18.7148285', '42.3288043', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (138, 'MW', 'Malawi', '-13.2331715', '32.0460163', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (139, 'MY', 'Malaysia', '4.1388513', '105.1102766', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (140, 'MV', 'Maldives', '1.9775842', '73.3956747', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (141, 'ML', 'Mali', '17.5339447', '-8.4921847', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (142, 'MT', 'Malta', '35.9444279', '14.2395984', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (143, 'MH', 'Marshall Islands', '6.068625', '171.8489502', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (144, 'MQ', 'Martinique', '14.6339718', '-61.1602513', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (145, 'MR', 'Mauritania', '20.9695529', '-15.4569274', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (146, 'MU', 'Mauritius', '-20.2004977', '56.5515453', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (147, 'YT', 'Mayotte', '-12.8205977', '45.018644', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (148, 'MX', 'Mexico', '23.3845931', '-111.5818973', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (149, 'FM', 'Micronesia', '6.8876466', '158.1448598', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (150, 'MD', 'Moldova', '46.9758013', '27.2659311', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (151, 'MC', 'Monaco', '43.7383525', '7.4069056', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (152, 'MN', 'Mongolia', '46.5264458', '94.8404046', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (153, 'ME', 'Montenegro', '42.7009484', '18.2718281', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (154, 'MS', 'Montserrat', '16.7495264', '-62.2630583', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (155, 'MA', 'Morocco', '31.7249211', '-11.5877298', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (156, 'MZ', 'Mozambique', '-18.6055326', '31.0216565', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (157, 'MM', 'Myanmar (Burma)', '18.8737176', '87.6198972', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (158, 'NA', 'Namibia', '-22.8933045', '13.9883388', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (159, 'NR', 'Nauru', '-0.5283715', '166.9166858', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (160, 'NP', 'Nepal', '28.3838239', '81.8808469', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (161, 'NL', 'Netherlands', '52.1950016', '3.0314973', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (162, 'NC', 'New Caledonia', '-21.2044482', '164.7277458', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (163, 'NZ', 'New Zealand', '-43.0116645', '163.4579715', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (164, 'NI', 'Nicaragua', '12.8694503', '-86.2652124', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (165, 'NE', 'Niger', '17.556586', '3.5739462', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (166, 'NG', 'Nigeria', '9.0610116', '4.1698842', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (167, 'NU', 'Niue', '-19.0538779', '-169.9322703', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (168, 'NF', 'Norfolk Island', '-29.0346262', '167.9219222', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (169, 'MP', 'Northern Mariana Islands', '15.1067129', '145.5658198', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (170, 'KP', 'North Korea', '40.3248783', '125.2094814', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (171, 'NO', 'Norway', '64.3114584', '8.942095', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (172, 'OM', 'Oman', '21.477641', '51.414045', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (173, 'PK', 'Pakistan', '30.325111', '64.848881', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (174, 'PW', 'Palau', '7.3669385', '134.1532754', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (175, 'PS', 'Palestine', '31.9472798', '34.6653486', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (176, 'PA', 'Panama', '8.4266397', '-81.2293981', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (177, 'PG', 'Papua New Guinea', '-6.2344217', '144.4562585', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (178, 'PY', 'Paraguay', '-23.4135546', '-60.6975238', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (179, 'PE', 'Peru', '-9.0605917', '-84.0507833', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (180, 'PH', 'Philippines', '11.6734327', '118.1144508', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (181, 'PN', 'Pitcairn Islands', '-24.3766629', '-128.3593406', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (182, 'PL', 'Poland', '51.8399358', '14.6381939', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (183, 'PT', 'Portugal', '39.5397582', '-10.1022675', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (184, 'PR', 'Puerto Rico', '18.1992069', '-66.9145068', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (185, 'QA', 'Qatar', '25.3272819', '50.6348335', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (186, 'RE', 'Réunion', '-21.1303107', '55.3860517', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (187, 'RO', 'Romania', '45.923722', '22.7611828', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (188, 'RU', 'Russia', '49.7802809', '68.7230077', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (189, 'RW', 'Rwanda', '-1.9421906', '29.3185984', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (190, 'WS', 'Samoa', '-13.7573093', '-172.385643', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (191, 'SM', 'San Marino', '43.9429344', '12.424988', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (192, 'ST', 'São Tomé and Príncipe', '0.2000379', '6.4701356', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (193, 'SA', 'Saudi Arabia', '24.210588', '40.602818', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (194, 'SN', 'Senegal', '14.5001595', '-15.5632449', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (195, 'RS', 'Serbia', '44.1926554', '18.674068', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (196, 'SC', 'Seychelles', '-4.6836294', '55.3792663', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (197, 'SL', 'Sierra Leone', '8.4507704', '-12.9110913', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (198, 'SG', 'Singapore', '1.3150701', '103.7065904', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (199, 'SX', 'Sint Maarten', '18.0347444', '-63.1032168', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (200, 'SK', 'Slovakia', '48.6688314', '18.5723109', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (201, 'SI', 'Slovenia', '46.148742', '14.4242239', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (202, 'SB', 'Solomon Islands', '-9.2139325', '156.9377652', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (203, 'SO', 'Somalia', '5.1583541', '41.6958682', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (204, 'ZA', 'South Africa', '-28.3954236', '20.1691651', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (205, 'GS', 'South Georgia and South Sandwich Islands', '-54.4360635', '-37.5486565', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (206, 'KR', 'South Korea', '35.8450139', '124.8476035', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (207, 'SS', 'South Sudan', '7.8621474', '27.4452126', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (208, 'ES', 'Spain', '40.1297111', '-8.2133227', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (209, 'LK', 'Sri Lanka', '7.8784478', '79.5763084', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (210, 'BL', 'St. Barthélemy', '17.9139874', '-62.8689575', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (211, 'SH', 'St. Helena', '-15.961984', '-5.7485247', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (212, 'KN', 'St. Kitts and Nevis', '17.2564735', '-62.8423923', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (213, 'LC', 'St. Lucia', '13.9098179', '-61.1168096', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (214, 'MF', 'St. Martin', '18.0652427', '-63.097167', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (215, 'PM', 'St. Pierre and Miquelon', '46.9468366', '-56.4027109', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (216, 'VC', 'St. Vincent and Grenadines', '13.2529754', '-61.2673747', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (217, 'SD', 'Sudan', '15.7502795', '25.6925707', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (218, 'SR', 'Suriname', '3.9252836', '-57.1348033', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (219, 'SJ', 'Svalbard and Jan Mayen', '78.5038212', '13.0499081', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (220, 'SZ', 'Swaziland', '-26.5153315', '30.9009627', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (221, 'SE', 'Sweden', '61.9175477', '8.6057795', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (222, 'CH', 'Switzerland', '46.8095683', '7.1004424', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (223, 'SY', 'Syria', '34.7987402', '36.7975981', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (224, 'TW', 'Taiwan', '23.5515988', '119.8971296', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (225, 'TJ', 'Tajikistan', '38.8408995', '68.9993391', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (226, 'TZ', 'Tanzania', '-6.3423327', '30.3849039', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (227, 'TH', 'Thailand', '13.0106473', '96.9829672', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (228, 'TL', 'Timor-Leste', '-8.792984', '125.5755697', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (229, 'TG', 'Togo', '8.6253336', '-1.4173121', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (230, 'TK', 'Tokelau', '-9.1667473', '-171.8533165', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (231, 'TO', 'Tonga', '-21.2414105', '-175.2689746', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (232, 'TT', 'Trinidad and Tobago', '10.4439567', '-61.7007123', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (233, 'TA', 'Tristan da Cunha', '-37.116132', '-12.3190814', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (234, 'TN', 'Tunisia', '33.7773333', '7.3118595', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (235, 'TR', 'Turkey', '38.8794951', '30.7409535', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (236, 'TM', 'Turkmenistan', '38.8858767', '55.0768576', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (237, 'TC', 'Turks and Caicos Islands', '21.7142208', '-72.2529924', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (238, 'TV', 'Tuvalu', '-7.4783777', '178.6623715', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (239, 'UM', 'U.S. Outlying Islands', '19.2954137', '166.6104916', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (240, 'VI', 'U.S. Virgin Islands', '18.3437159', '-65.0075918', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (241, 'UG', 'Uganda', '1.3725984', '30.053501', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (242, 'UA', 'Ukraine', '48.302593', '26.6854126', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (243, 'AE', 'United Arab Emirates', '24.3489463', '52.815674', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (244, 'GB', 'United Kingdom', '55.0451555', '-12.4175147', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (245, 'US', 'United States', '36.2426686', '-113.7457857', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (246, 'UY', 'Uruguay', '-32.5336862', '-58.0604255', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (247, 'UZ', 'Uzbekistan', '41.3017107', '60.073659', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (248, 'VU', 'Vanuatu', '-15.432576', '165.345944', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (249, 'VA', 'Vatican City', '41.9038243', '12.4476731', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (250, 'VE', 'Venezuela', '6.6476415', '-71.1224244', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (251, 'VN', 'Vietnam', '15.8669585', '101.2999618', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (252, 'WF', 'Wallis and Futuna', '-14.3012954', '-178.1259679', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (253, 'EH', 'Western Sahara', '24.2072415', '-15.1353425', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (254, 'YE', 'Yemen', '15.5477952', '45.9255044', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (255, 'ZM', 'Zambia', '-13.0904028', '23.3474606', 0);
INSERT INTO `mydb`.`country` (`id`, `code`, `latin_name`, `lat`, `lon`, `can_delete`) VALUES (256, 'ZW', 'Zimbabwe', '-18.9970366', '26.9034543', 0);

COMMIT;

